# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0016_auto_20170629_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsconfiguration',
            options={'verbose_name': 'Configuraci\xf3n SMS'},
        ),
    ]
