# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0017_auto_20170706_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=256, verbose_name='Descripci\xf3n')),
                ('key', models.CharField(blank=True, max_length=256, null=True, verbose_name='Llave')),
                ('secret', models.CharField(blank=True, max_length=256, null=True, verbose_name='Secreto')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='De')),
                ('callback', models.CharField(blank=True, max_length=256, null=True, verbose_name='Callback')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Backend',
                'verbose_name_plural': 'Backends',
            },
        ),
        migrations.AlterField(
            model_name='smsconfiguration',
            name='SMSBackend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Backend'),
        ),
    ]
