# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cacaosms', '0019_auto_20170822_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfiguration',
            name='SMSBackend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cacaosms.Backend'),
        ),
    ]
